openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Go Car API'
  description: Manage Cars
  servers:
    - url: http://localhost:8080/api/

paths:
  /car/{id}:
    parameters:
      - name: id
        description: The unique identifier of the car
        in: path
        required: true
    get:
      summary: Get Car by ID
      responses:
        '200':
          description: Get the car corresponding to the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: No car found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update Car by ID
      responses:
        '200':
          description: Update the car corresponding to the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: No car found for the provided `id`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'                
    post:
      summary: Add Car
      responses:
        '200':
          description: The car
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Car'
        '404':
          description: Unable to add car
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    id:
      description: The unique identifier of a car
      type: string
    Make:
      description: Make of the car
      type: string
    Model:
      description: Model of the car
      type: string
    Package:
      description: Package of the car
      type: string
    Color:
      description: Color of the car
      type: string
    Year:
      description: Year of the car
      type: string
    Category:
      description: Category of the car
      type: string
    Mileage:
      description: Number of miles on the car
      type: uint
    Price:
      description: Price of the car
      type: uint
    
    Car:
      type: object
      required:
        - id
        - Make
        - Model
        - Package
        - Color
        - Year
        - Category
        - Mileage
        - Price
      

    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string